[package]
name = "sleipnir"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Memory safe font operations for Google Fonts."
repository = "https://github.com/googlefonts/sleipnir"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
kurbo = "0.10.4"
skrifa = "0.17.0"
write-fonts = "0.17.0"

smol_str = "0.2.1"
thiserror = "1.0.57"

[dev-dependencies]
pretty_assertions = "1.3.0"
