[package]
name = "sleipnir"
version = "0.1.3"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Memory safe font operations for Google Fonts."
repository = "https://github.com/googlefonts/sleipnir"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
kurbo = "0.11.0"
regex = "1.10.4"
skrifa = "0.19.0"

smol_str = "0.2.1"
thiserror = "1.0.57"

[dev-dependencies]
pretty_assertions="1.4"

[patch.crates-io]
read-fonts = { git = "https://github.com/googlefonts/fontations", branch = "abstract_glyf_point" }
